# Generated by Django 3.2 on 2025-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loomvideo',
            name='transcript',
            field=models.CharField(max_length=60000),
        ),
    ]
