# Generated by Django 3.2 on 2025-06-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loom', '0003_alter_loomvideo_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loomvideo',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='loomvideo',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='loomvideo',
            name='transcript',
            field=models.CharField(blank=True, max_length=6000),
        ),
    ]
